services:
  Database.Session:
    module: src.contexts.shared.infrastructure.persistence.sqlite.db
    class:
      name: SQLiteDB
    method:
      name: create_session
      arguments:
        - sqlite:///./database.db
        - false
        - false
