services:
  Database.Session:
    class: src.contexts.shared.infrastructure.persistence.sqlite.db.SQLiteDB
    factory_method: create_session
    arguments:
      - sqlite:///./database.db
      - false
      - false

  QueryBus:
    class: src.contexts.shared.infrastructure.bus.query.in_memory_query_bus.InMemoryQueryBus
    arguments:
      - !tagged query_handler

  CommandBus:
    class: src.contexts.shared.infrastructure.bus.command.in_memory_command_bus.InMemoryCommandBus
    arguments:
      - !tagged command_handler
