@base_url = http://127.0.0.1:8000/api/v1

###
GET {{base_url}}/beers


###
@beer_id = 37dfb8f97e2c4a478fc2e11ec64666b8

GET {{base_url}}/beers/{{beer_id}}


###
POST {{base_url}}/beers
Content-Type: application/json

{
  "name": "New Beer 1",
  "type": "IPA",
  "alcohol": 6.5,
  "description": "A new beer description"
}


###
@beer_id = 37dfb8f97e2c4a478fc2e11ec64666b8

PUT {{base_url}}/beers/{{beer_id}}
Content-Type: application/json

{
  "name": "New Beer",
  "type": "IPA",
  "alcohol": 6.5,
  "description": "A new beer description"
}


###
@beer_id = 37dfb8f97e2c4a478fc2e11ec64666b8

DELETE {{base_url}}/beers/{{beer_id}}
