services:
  # Repositoies
  BeerRepository:
    class: src.contexts.beer.beer.infrastructure.persistence.sqlite.beer_repository.SqliteBeerRepository
    arguments:
      - "@Database.Session"

  StoreRepository:
    class: src.contexts.beer.store.infrastructure.persistence.sqlite.store_repository.SqliteStoreRepository
    arguments:
      - "@Database.Session"

  # Query Handlers
  SearchBeerByCriteriaQueryHandler:
    class: src.contexts.beer.beer.application.query.search_by_criteria_query_handler.SearchBeerByCriteriaQueryHandler
    arguments:
      - "@BeerRepository"
    tags:
      - query_handler

  FindBeerByIdQueryHandler:
    class: src.contexts.beer.beer.application.query.find_by_id_query_handler.FindBeerByIdQueryHandler
    arguments:
      - "@BeerRepository"
    tags:
      - query_handler

  SearchStoreByCriteriaQueryHandler:
    class: src.contexts.beer.store.application.query.search_by_criteria_query_handler.SearchStoreByCriteriaQueryHandler
    arguments:
      - "@StoreRepository"
    tags:
      - query_handler

  FindStoreByIdQueryHandler:
    class: src.contexts.beer.store.application.query.find_by_id_query_handler.FindStoreByIdQueryHandler
    arguments:
      - "@StoreRepository"
    tags:
      - query_handler

  # Command Handlers
  RegisterBeerCommandHandler:
    class: src.contexts.beer.beer.application.command.register_command_handler.RegisterBeerCommandHandler
    arguments:
      - "@BeerRepository"
    tags:
      - command_handler

  UpdateBeerCommandHandler:
    class: src.contexts.beer.beer.application.command.update_command_handler.UpdateBeerCommandHandler
    arguments:
      - "@BeerRepository"
    tags:
      - command_handler

  DeleteBeerCommandHandler:
    class: src.contexts.beer.beer.application.command.delete_command_handler.DeleteBeerCommandHandler
    arguments:
      - "@BeerRepository"
    tags:
      - command_handler

  RegisterStoreCommandHandler:
    class: src.contexts.beer.store.application.command.register_command_handler.RegisterStoreCommandHandler
    arguments:
      - "@StoreRepository"
    tags:
      - command_handler

  UpdateStoreCommandHandler:
    class: src.contexts.beer.store.application.command.update_command_handler.UpdateStoreCommandHandler
    arguments:
      - "@StoreRepository"
    tags:
      - command_handler

  DeleteStoreCommandHandler:
    class: src.contexts.beer.store.application.command.delete_command_handler.DeleteStoreCommandHandler
    arguments:
      - "@StoreRepository"
    tags:
      - command_handler
